### ISSUE TITLE
Morning announcement duration wrong

### ISSUE THREAD

**Issue by hypha** [EuroPython/programapi#143]
- On pretalx, the duration for morning announcement is 15 min, e.g. https://programme.europython.eu/europython-2025/talk/9CERQG/
- On programmeapi, it's 30 min. 

This results in the sessions overlapping with each other on our schedule as shown here: 

<img width="274" height="299" alt="Thursday morning announcement overlapping with the keynote next on schedule" src="https://github.com/user-attachments/assets/aaf322f6-bc73-48b3-9658-8c6e4174f8e7" />

And since discord pulls from programmeapi, it will probably also reports the wrong time.

**Comment by egeakman** [comment]
Fixed it on Pretalx, should be fixed on the website soon

**Comment by hypha** [comment]
Oh thank you so much! Was it one of those situations where the schedule on pretalx was showing correct timing  but the duration in the talk listing was still wrong?

**Comment by egeakman** [comment]
> Oh thank you so much! Was it one of those situations where the schedule on pretalx was showing correct timing but the duration in the talk listing was still wrong?

Yes, the default duration of the type `announcement` is 30 minutes. If we use that type but have a different duration, we need to input something in the `Duration` field on pretalx.

**Comment by egeakman** [comment]
<img width="1919" height="827" alt="Image" src="https://github.com/user-attachments/assets/ee5b0a8d-6e74-4791-9e33-a10ae223a787" />

Closing the issue since it looks OK.

**Comment by hypha** [comment]
Thank you so much, Ege!
